name: UI Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      LOGIN: ${{ secrets.LOGIN }}
      PASSWORD: ${{ secrets.PASSWORD }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build container
        run: docker compose build

      - name: Run tests
        run: docker compose run --rm regression
        continue-on-error: true

      - name: Copy allure results from container run
        if: always()
        run: |
          mkdir -p allure-results
          ls -la

      - name: Generate Allure report
        if: always()
        run: |
          docker compose run --rm regression \
            /bin/sh -c "allure generate allure-results -o allure-report --clean"

      - name: Upload Allure report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy report
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: allure-report